### ISSUE TITLE
Marker not showing (on client 1.14.2)

### ISSUE THREAD

**Issue by pairofdocs** [adrianocastro189/multi-targets#44]
Hello,

Nice work on the addon!

I was trying to get this to work on client 1.14.2
Using MultiTargets 1.3.2 I can see the Multitargets window, the "+ add target / - remove target" button over a target frame 
but I can't see a marker in-game on the target after clicking add target.

adding print logging to TargetList.lua I can see that
`function TargetList:refreshState(action)` is called,  `self:sanitizeMarks()` is called, `self:updateMacroWithCurrentTarget()` is called

The macro is updated to
```
/cleartarget
/target Wretched Zombie
/cleartarget [dead]
/run MultiTargets:invokeOnCurrent('maybeMark')
/run C_Timer.After(0.1, function() MultiTargets:invokeOnCurrent('rotate') end)
```

Any ideas on what could be preventing a marker to be set for the added unit?

Edit:
I figured it out. Part user error and part lua update.
I had to set the macro icon to `self:setIcon('INV_Misc_QuestionMark')` since `ability_hunter_focusedaim` wasn't working

**Comment by adrianocastro189** [comment]
Hey there, thanks for pointing out that! I'll keep it in mind for future releases.
Unfortunately, due to other priorities I had to focus, my addons are a bit outdated and I'm intending to retake the work on them on the future.
But I'm glad you figured out how to solve.
